{{- if .Values.istio.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-{{ include "deployment.fullname" . }}-canary
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    app.kubernetes.io/name: model-{{ include "deployment.name" . }}
spec:
  replicas: {{ .Values.istio.canary.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: model-{{ include "deployment.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      version: canary
  template:
    metadata:
      labels:
        {{- include "deployment.labels" . | nindent 8 }}
        app.kubernetes.io/name: model-{{ include "deployment.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        version: canary
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "deployment.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.istio.canary.modelImage.repository }}:{{ .Values.istio.canary.modelImage.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.model.targetPort }}
              protocol: TCP
          env:
            - name: MODEL_HOST
              value: "http://{{ .Values.services.model.name }}:{{ .Values.services.model.port | default 8081 }}"
            - name: MODEL_SERVICE_PORT
              value: "8081"
            - name: CONFIG_TEST
              valueFrom:
                configMapKeyRef:
                  name: model-configmap
                  key: config_test
            - name: DUMMY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: model-secret
                  key: api_key
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
