apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-{{ include "deployment.fullname" . }}-shadow
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    app.kubernetes.io/name: model-{{ include "deployment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-shadow
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: model-{{ include "deployment.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}-shadow
  template:
    metadata:
      labels:
        {{- include "deployment.labels" . | nindent 8 }}
        app.kubernetes.io/name: model-{{ include "deployment.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-shadow
        version: shadow
    spec:
      serviceAccountName: {{ include "deployment.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-shadow
          image: "{{ .Values.image.model.repository }}:{{ .Values.image.model.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.model.targetPort }}
              protocol: TCP
          env:
            - name: MODEL_HOST
              value: "http://model-service:8081"
            - name: MODEL_SERVICE_PORT
              value : "8081"
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
