{{- if and .Values.prometheus.enabled .Values.prometheus.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "deployment.fullname" . }}-alerts
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    release: {{ .Values.prometheus.releaseLabel }}
    role: alert-rules
spec:
  groups:
    - name: sms-checker-alerts
      rules:
        - alert: HighRequestRate
          expr: rate(sms_classification_requests_total[1m]) * 60 > 10
          for: 10s
          labels:
            severity: critical
            service: sms-checker
          annotations:
            summary: "High request rate on SMS Checker"
            description: 'SMS Checker receiving >10 req/min for 10 seconds (Current: {{ printf "{{ $value | humanize }}" }} req/min)'
{{- end }}
